<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $date = date("Y-m-d H:s:i", time());

        DB::table('payments')->insert(array(
              array(
                    'id' => 1,
                    'product_id' => 1,
                    'buyer_id' => 1,
                    'buyer' => 'samuel',
                    'dispatcher' => 'withwicky',
                    'product_name' => 'phone',
                    'product_price' => 20000,
                    'installment_amount' => 2,
                    'first' => 8000,
                    'second' => 12000,
                    'third' => 0,
                    'fourth' => 0,
                    'sixth' => 0,
                    'fifth' => 0,
                    'first_date_payed' => $date,
                    'second_date_payed' => $date,
                    'third_date_payed' => null,
                    'fourth_date_payed' => null,
                    'fifth_date_payed' => null,
                    'sixth_date_payed' => null,
                    'return' => 0,
                    'delivered' => 0,
                    'date_supplied' => $date
                ),
              array(
                'id' => 2,
                'product_id' => 2,
                'buyer_id' => 2,
                'buyer' => 'simeon',
                'dispatcher' => 'simons',
                'product_name' => 'laptop',
                'product_price' => 70000,
                'installment_amount' => 3,
                'first' => 25000,
                'second' => 25000,
                'third' => 25000,
                'fourth' => 0,
                'sixth' => 0,
                'fifth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => null,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 0,
                'delivered' => 1,
                'date_supplied' => $date
            ),
            array(
                'id' => 3,
                'product_id' => 3,
                'buyer_id' => 3,
                'buyer' => 'micheal',
                'dispatcher' => 'bay',
                'product_name' => 'ladies gown',
                'product_price' => 30000,
                'installment_amount' => 3,
                'first' => 15000,
                'second' => 5000,
                'third' => 10000,
                'fourth' => 0,
                'sixth' => 0,
                'fifth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => null,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 0,
                'delivered' => 1,
                'date_supplied' => $date
            ),
            array(
                'id' => 4,
                'product_id' => 4,
                'buyer_id' => 4,
                'buyer' => 'adam',
                'dispatcher' => 'sandlars',
                'product_name' => 'bag',
                'product_price' => 20000,
                'installment_amount' => 2,
                'first' => 15000,
                'second' => 5000,
                'third' => 0,
                'fourth' => 0,
                'sixth' => 0,
                'fifth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => null,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 1,
                'delivered' => 1,
                'date_supplied' => $date
            ),
            array(
                'id' => 5,
                'product_id' => 5,
                'buyer_id' => 5,
                'buyer' => 'jackie',
                'dispatcher' => 'chan',
                'product_name' => 'men shoe',
                'product_price' => 40000,
                'installment_amount' => 4,
                'first' => 15000,
                'second' => 10000,
                'third' => 7000,
                'fourth' => 8000,
                'sixth' => 0,
                'fifth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => $date,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 0,
                'delivered' => 1,
                'date_supplied' => $date
            ),
            array(
                'id' => 6,
                'product_id' => 6,
                'buyer_id' => 6,
                'buyer' => 'johny',
                'dispatcher' => 'cage',
                'product_name' => 'necklace',
                'product_price' => 80000,
                'installment_amount' => 5,
                'first' => 30000,
                'second' => 15000,
                'third' => 15000,
                'fourth' => 1000,
                'fifth' => 10000,
                'sixth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => $date,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 1,
                'delivered' => 0,
                'date_supplied' => $date
            ),
            array(
                'id' => 7,
                'product_id' => 7,
                'buyer_id' => 7,
                'buyer' => 'charles',
                'dispatcher' => 'udoh',
                'product_name' => 'speaker',
                'product_price' => 38000,
                'installment_amount' => 4,
                'first' => 9000,
                'second' => 20000,
                'third' => 5000,
                'fourth' => 4000,
                'fifth' => 0,
                'sixth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => $date,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 0,
                'delivered' => 1,
                'date_supplied' => $date
            ),
            array(
                'id' => 8,
                'product_id' => 8,
                'buyer_id' => 8,
                'buyer' => 'micheal',
                'dispatcher' => 'sam',
                'product_name' => 'speaker',
                'product_price' => 60000,
                'installment_amount' => 5,
                'first' => 24000,
                'second' => 15000,
                'third' => 9000,
                'fourth' => 7000,
                'fifth' => 5000,
                'sixth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => $date,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 0,
                'delivered' => 1,
                'date_supplied' => $date
            ),
            array(
                'id' => 9,
                'product_id' => 9,
                'buyer_id' => 9,
                'buyer' => 'chibueze',
                'dispatcher' => 'olorunda',
                'product_name' => 'phone',
                'product_price' => 50000,
                'installment_amount' => 4,
                'first' => 15000,
                'second' => 15000,
                'third' => 1000,
                'fourth' => 10000,
                'fifth' => 0,
                'sixth' => 0,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => $date,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 0,
                'delivered' => 1,
                'date_supplied' => $date
            ),
            array(
                'id' => 10,
                'product_id' => 10,
                'buyer_id' => 10,
                'buyer' => 'ifeoluwa',
                'dispatcher' => 'demola',
                'product_name' => 'necklace',
                'product_price' => 120000,
                'installment_amount' => 6,
                'first' => 45000,
                'second' => 17000,
                'third' => 12000,
                'fourth' => 17000,
                'fifth' => 13000,
                'sixth' => 16000,
                'first_date_payed' => $date,
                'second_date_payed' => $date,
                'third_date_payed' => $date,
                'fourth_date_payed' => $date,
                'fifth_date_payed' => null,
                'sixth_date_payed' => null,
                'return' => 0,
                'delivered' => 1,
                'date_supplied' => $date
            ),
        ));
    }
}



